# Cloudflare Pages Build Configuration
# This file defines build settings for Cloudflare Pages deployment

build:
  command: bundle exec jekyll build
  output_directory: _site

environment:
  RUBY_VERSION: "3.2.0"
  JEKYLL_ENV: production
