name: Update Latest Commits

on:
  schedule:
    - cron: '0 0 * * *'  # daily at midnight UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update_commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Fetch commits and sort by date
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "---" > commits.md
          echo "layout: default" >> commits.md
          echo "title: Latest Commits" >> commits.md
          echo "permalink: /commits/" >> commits.md
          echo "---" >> commits.md
          echo "" >> commits.md
          echo "# Latest Commits Across All Projects" >> commits.md
          echo "" >> commits.md

          # Collect all commits from all repos
          COMMITS_JSON=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/users/OleksSobol/repos?per_page=100" \
            | jq -r '.[].name' \
            | while read repo; do
                curl -s -H "Authorization: token $GITHUB_TOKEN" \
                  "https://api.github.com/repos/OleksSobol/$repo/commits?per_page=10" \
                  | jq -r ".[] | {repo: \"$repo\", message: .commit.message, date: .commit.author.date, url: .html_url}" 
              done
          )
          
          # Sort all commits by date descending and format
          echo "$COMMITS_JSON" | jq -s '
          sort_by(.date) | reverse | .[] |
          "- [\(.repo)](\(.url)): \(.message) (\(.date | split("T")[0]))"
          ' >> commits.md
          
      - name: Commit changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add commits.md
          git commit -m "Update latest commits" || echo "No changes"
          git push
